# Generated by Django 5.2.8 on 2025-11-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationprovider',
            name='img_url',
            field=models.CharField(default='hi'),
            preserve_default=False,
        ),
    ]
