# Generated by Django 5.2.8 on 2025-11-11 18:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationprovider_img_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integrationconnection',
            unique_together={('user', 'provider', 'external_id')},
        ),
    ]
