# Generated by Django 5.2.8 on 2025-11-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_integrationconnection_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationprovider',
            name='img_url',
        ),
    ]
