# Generated by Django 5.2.8 on 2025-11-23 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_tool'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tool',
            name='slug_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='integrations.integrationprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('display_name', 'provider', 'slug_name')},
        ),
    ]
