# Generated by Django 5.2.8 on 2025-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_tool_unique_together_tool_slug_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationprovider',
            name='has_cloud_agent',
            field=models.BooleanField(default=False),
        ),
    ]
