# Generated by Django 5.2.8 on 2025-11-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_integrationprovider_has_cloud_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_model',
            field=models.BooleanField(default=False),
        ),
    ]
