# Generated by Django 5.2.8 on 2025-11-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='github_id',
            new_name='github_repository_id',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='uuid',
        ),
        migrations.AddField(
            model_name='workspace',
            name='github_branch_name',
            field=models.CharField(null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField()),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AGENT', 'Agent')], max_length=5)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
    ]
