# Generated by Django 5.2.8 on 2025-11-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_rename_github_id_workspace_github_repository_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='github_repository_id',
        ),
        migrations.AddField(
            model_name='workspace',
            name='github_repository_name',
            field=models.CharField(default='test', editable=False),
            preserve_default=False,
        ),
    ]
