# Generated by Django 5.2.8 on 2025-11-13 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_remove_workspace_github_repository_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='Untitled', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
