# Generated by Django 5.2.8 on 2025-11-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_workspace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField()),
                ('result', models.TextField()),
                ('status', models.CharField(default='success', max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='workspaces.message')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
