# Generated by Django 5.2.8 on 2025-11-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspace_status_toolcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='github_repository_name',
            field=models.CharField(),
        ),
    ]
