# Generated by Django 5.2.8 on 2025-11-23 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_tool_unique_together_tool_slug_name_and_more'),
        ('workspaces', '0006_alter_workspace_github_repository_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.tool')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='tools',
            field=models.ManyToManyField(related_name='workspaces', through='workspaces.WorkspaceTool', to='integrations.tool'),
        ),
    ]
