# Generated by Django 5.2.8 on 2025-11-24 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_tool_unique_together_tool_slug_name_and_more'),
        ('workspaces', '0007_workspacetool_workspace_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workerdefinition'),
        ),
        migrations.CreateModel(
            name='WorkerDefinitionTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.tool')),
                ('worker_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workerdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='workerdefinition',
            name='tools',
            field=models.ManyToManyField(related_name='workerDefinitions', through='workspaces.WorkerDefinitionTool', to='integrations.tool'),
        ),
    ]
