# Generated by Django 5.2.8 on 2025-11-26 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workerdefinition_workspace_worker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdefinition',
            name='slug',
            field=models.CharField(default='slug', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workerdefinition',
            unique_together={('slug', 'user')},
        ),
    ]
