# Generated by Django 5.2.8 on 2025-11-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workerdefinition_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdefinition',
            name='key',
            field=models.CharField(null=True),
        ),
    ]
