# Generated by Django 5.2.8 on 2025-11-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_workerdefinition_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('Cursor', 'Cursor'), ('Jules', 'Jules')], max_length=10)),
                ('conversation_id', models.CharField(max_length=200)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
    ]
