# Generated by Django 5.2.8 on 2025-11-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_provideragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideragent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_agents', to='workspaces.workspace'),
        ),
    ]
