# Generated by Django 5.2.8 on 2025-11-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_alter_provideragent_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideragent',
            name='url',
            field=models.CharField(default='test'),
            preserve_default=False,
        ),
    ]
