# Generated by Django 5.2.8 on 2025-11-30 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_provideragent_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='toolcall',
            name='workspace',
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('Codee', 'Codee'), ('Cursor', 'Cursor'), ('Jules', 'Jules')], max_length=10)),
                ('conversation_id', models.CharField(max_length=200)),
                ('url', models.CharField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_agents', to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workspaces.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolcall',
            name='agent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='workspaces.agent'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProviderAgent',
        ),
    ]
