# Generated by Django 5.2.8 on 2025-11-30 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_remove_message_workspace_remove_toolcall_workspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='github_branch_name',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='status',
        ),
        migrations.AddField(
            model_name='agent',
            name='github_branch_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='Untitled', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
