# Generated by Django 5.2.8 on 2025-11-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0015_remove_workspace_github_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
