# Generated by Django 5.2.8 on 2025-12-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_agent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdefinition',
            name='cloud_providers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
