# Generated by Django 5.2.8 on 2025-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_alter_workerdefinition_cloud_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdefinition',
            name='cloud_providers',
            field=models.JSONField(default=list),
        ),
    ]
