# Generated by Django 5.2.8 on 2025-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('uuid', models.UUIDField(editable=False)),
            ],
        ),
    ]
