# Generated by Django 5.2.8 on 2025-11-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
